function result = runPipeline(image, cfg)
%RUNPIPELINE Execute the M1-M5 RetinaScan AI pipeline.

quality = retinascan.m1.assessQuality(image, cfg.m1);

if quality.isGradeable
    preprocessed = retinascan.m1.preprocessImage(image, cfg.m1);
    segments = retinascan.m2.segmentStructures(preprocessed.image, cfg.m2);
    grade = retinascan.m3.gradeDR(preprocessed.image, cfg.m3);
    explanation = retinascan.m4.explainPrediction(preprocessed.image, grade, segments, cfg.m4);
else
    preprocessed = struct('image', [], 'method', 'not_applied', 'notes', {{'Image rejected by quality gate.'}});
    segments = struct('enabled', false, 'masks', struct(), 'findings', {{'Skipped because image was not gradeable.'}});
    grade = struct( ...
        'icdrLevel', NaN, ...
        'classLabel', 'ungradeable', ...
        'referableDR', false, ...
        'confidence', 0.0, ...
        'modelVersion', cfg.project.model_version, ...
        'notes', {{'No DR grade assigned because image was rejected.'}} ...
    );
    explanation = struct('heatmap', [], 'method', 'not_applied', 'notes', {{'Skipped because image was not gradeable.'}});
end

throughput = retinascan.m5.simulateThroughput(cfg.m5);
report = retinascan.report.buildClinicalReport(quality, grade, explanation, cfg.report);

result = struct( ...
    'quality', quality, ...
    'preprocessed', preprocessed, ...
    'segments', segments, ...
    'grade', grade, ...
    'explanation', explanation, ...
    'throughput', throughput, ...
    'report', report ...
);
end
